### ISSUE TITLE
GET /book/{isbn} should include more data

### ISSUE THREAD

**Issue by redbassett** [hawkw/Alexandria#15]
Fields to add:
- weight (string)
- pages (integer)
- publish date (string)
- publisher (string)
- dewy decimal (array of string)
- subtitle (string)

Convert:
- authors to array of string

**Comment by redbassett** [comment]
Relevant properties:
```
definitions:
  Book:
    properties:
      isbn:
        type: string
      title:
        type: string
      subtitle:
        type: string
      authors:
        type: array
        item:
          type: string
      publisher:
        type: string
      published_date:
        type: string
      pages:
        type: integer
```
